#!/bin/bash

UBUNTU="bionic"
UBUNTU_ARCH="amd64"

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. ${ONHOST}/config

. ${ONHOST}/setup/ubuntu
. ${ONHOST}/setup/ubuntu-kernel
. ${ONHOST}/setup/boot