#!/bin/bash

UBUNTU="bionic"
UBUNTU_ARCH="amd64"

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. ${ONHOST}/config
baremetal_config

alternate_wipe
altermate_partition
alternate_md
alternate_format
alternate_mount_baremetal

. ${ONHOST}/setup/ubuntu
. ${ONHOST}/setup/ubuntu-kernel

alternate_bless