#!/bin/bash

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. ${ONHOST}/setup/detect-boot-device

localdisks=()
localparts=()
localmds=()
localfmts=()
localmounts=()

part ${BOOT_DEVICES[0]} 128 0700 10M efi
format ${BOOT_DEVICES[0]} 128 vfat -R 2 -S 512 -n EFI
mountfs ${BOOT_DEVICES[0]} 128 vfat /efi

part ${BOOT_DEVICES[0]} 127 8300 4086M boot
format ${BOOT_DEVICES[0]} 127 ext4
mountfs ${BOOT_DEVICES[0]} 127 ext4 /boot
locallegacyboot=("${BOOT_DEVICES[0]}:127")
