#!/bin/bash
ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

. ${ONHOST}/disklayout/boot

part ${BOOT_DEVICES[1]} 127 8300 4096M boot symmetry

md 1 0 ${BOOT_DEVICES[@]}

format md 1 ext4

mountfs md 1 ext4 /

md 2 0 ${NVMES[@]}

format md 2 ext4

mountfs md 2 ext4 /var/app/druid/storage