#!/bin/bash
ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

. ${ONHOST}/disklayout/boot

part ${BOOT_DEVICES[0]} 1 8300 256G root
format ${BOOT_DEVICES[0]} 1 ext4
mountfs ${BOOT_DEVICES[0]} 1 ext4 /

for disk in ${BOOT_DEVICES[@]}; do
  part $disk 2 8300 0 $(echo $disk|cut -f 3 -d '/')
  format $disk 2 ext4
  mountfs $disk 2 ext4 /hadoop2/$(echo $disk|cut -f 3 -d '/')
done
