#!/bin/bash
ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

. ${ONHOST}/disklayout/boot

md 1 0 ${NVMES[0]} ${NVMES[1]}
format md 1 ext4
mountfs md 1 ext4 /


part ${BOOT_DEVICES[1]} 127 8300 4096M boot symmetry
for disk in ${BOOT_DEVICES[@]}; do
  part $disk 2 8300 0 $(echo $disk|cut -f 3 -d '/')
  format $disk 2 ext4
  mountfs $disk 2 ext4 /hadoop2/$(echo $disk|cut -f 3 -d '/')
done
