#!/bin/bash

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. ${ONHOST}/disklayout/boot

part ${BOOT_DEVICES[0]} 1 8300
format ${BOOT_DEVICES[0]} 1 ext4
mountfs ${BOOT_DEVICES[0]} 1 ext4 /

part ${NVMES[0]} 2 8200 128g

part ${NVMES[0]} 1 8300
format ${NVMES[0]} 1 ext4
mountfs ${NVMES[0]} 1 ext4 /var/app
