#!/bin/bash

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. ${ONHOST}/disklayout/single-disk

part ${BOOT_DEVICES[1]} 1 8300
format ${BOOT_DEVICES[1]} 1 ext4
mountfs ${BOOT_DEVICES[1]} 1 ext4 /var/app

for disk in ${BOOT_DEVICES[@]:2}; do
  part $disk 2 8300 0 $(echo $disk|cut -f 3 -d '/')
  format $disk 2 ext4
  mountfs $disk 2 ext4 /hadoop2/$(echo $disk|cut -f 3 -d '/')
done