#!/bin/bash

KERNEL_OPTIONS="console=tty1 net.ifnames=0 biosdevname=0 raid0.default_layout=2 nvme_core.force_apst=1 nvme_core.default_ps_max_latency_us=200 pti=off noibrs noibpb nopti nospectre_v2 nospectre_v1 l1tf=off nospec_store_bypass_disable no_stf_barrier mds=off tsx_async_abort=off mitigations=off performance=good" # WARNING: pti=on unless you know what it means
BAREMETAL_ROOT="/mnt/baremetal"

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${ONHOST}/helper-dsl

baremetal_config() {
  echo Disks: ${DISKS[*]}
  echo NVMEs: ${NVMES[*]}
  echo
  echo Boot device is ${BOOT_DEVICES[0]}
  echo "---"
  echo "\$localdisks = all your disks are belong to us"
  for entry in "${localdisks[@]}"; do echo $entry; done
  echo "---"

  echo "\$localparts = partion disk:minor:type:size:label"
  for entry in "${localparts[@]}"; do echo $entry; done
  echo "---"

  echo "\$localmds = md minor:level:devices"
  for entry in "${localmds[@]}"; do echo $entry; done
  echo "---"

  echo "\$localfmts = device:type:options"
  for entry in "${localfmts[@]}"; do echo $entry; done
  echo "---"

  echo "\$localmounts = device:type:mountpoint:options"
  for entry in "${localmounts[@]}"; do echo $entry; done
  echo "---"
}
