#!/bin/bash

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. ${ONHOST}/setup/boot-device

# efi boot
cat <<E=O=F >${BAREMETAL_ROOT}/etc/default/grub.d/60-liquidm-settings.cfg
GRUB_CMDLINE_LINUX_DEFAULT="$KERNEL_OPTIONS"
E=O=F
spawn_chroot "grub-install --removable --target=x86_64-efi --boot-directory=/boot --efi-directory=/efi ${BOOT_DEVICE}"

# legacy boot
spawn_chroot "dd bs=440 count=1 conv=notrunc if=/usr/lib/EXTLINUX/gptmbr.bin of=${BOOT_DEVICE}"
spawn_chroot "extlinux --install /boot"
cd ${BAREMETAL_ROOT}/boot
cat <<E=O=F >${BAREMETAL_ROOT}/boot/extlinux.conf
DEFAULT linux
  SAY Legacy boot via EXTLINUX...
LABEL linux
  KERNEL `ls vmlinuz-*|tail -1`
  APPEND ro root=${BOOT_DEVICE}${PARTITON_PREFIX}3 initrd=`ls initrd.img*|tail -1` $KERNEL_OPTIONS
E=O=F

# default network config
device=$(ip route | awk '/default/ { print $5 }')
gateway=$(ip route list | grep default | awk '{ print $3 }')
ipaddress=$(ip addr show dev ${device} | grep 'inet .*global' | awk '{ print $2 }')

cat <<E=O=F >${BAREMETAL_ROOT}/etc/systemd/network/default.network
[Match]
Name=${device}

[Network]
Address=${ipaddress}
Gateway=${gateway}
E=O=F

