#!/bin/bash

ONHOST="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. ${ONHOST}/config

# check if there is a regular block device
if [[ "${BOOT_DEVICE}" == "" ]]; then
  BOOT_DEVICE=/dev/`lsblk -l|grep disk|cut -f 1 -d ' '|grep -v nvme|sort|head -1`
fi
# check if there is an nvme device
if [[ "${BOOT_DEVICE}" == "" ]]; then
  BOOT_DEVICE=/dev/`lsblk -l|grep disk|cut -f 1 -d ' '|grep nvme|sort|head -1`
fi

if [[ "${BOOT_DEVICE}" == nvme* ]]; then
  PARTITON_PREFIX="p"
else
  PARTITON_PREFIX=""
fi

export BOOT_DEVICE
export PARTITON_PREFIX

echo Installing on ${BOOT_DEVICE}, root will be ${BOOT_DEVICE}${PARTITON_PREFIX}3