#!/bin/bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd $ROOT_DIR
echo assuming $ROOT_DIR as root directory of baremetal-cloud

curl -s -k -L http://git.io/bootstrap-rvm-bundler | bash -s
cd $ROOT_DIR
rvm install `cat .ruby-version`
cd $ROOT_DIR
gem install bundler
bundle install
